name = "paris-dev"
main = "src/index.ts"
compatibility_date = "2025-12-28"
workers_dev = true

[[queues.producers]]
binding = "L10N_GENERATE_QUEUE"
queue = "instance-l10n-generate-cloud-dev"

[[queues.producers]]
binding = "L10N_PUBLISH_QUEUE"
queue = "instance-l10n-publish-cloud-dev"

[[triggers.crons]]
cron = "*/5 * * * *"

[env.local]
name = "paris-local"

[[env.local.queues.producers]]
binding = "L10N_GENERATE_QUEUE"
queue = "instance-l10n-generate-local"

[[env.local.queues.producers]]
binding = "L10N_PUBLISH_QUEUE"
queue = "instance-l10n-publish-local"
