name = "roma-dev"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-12-28"
compatibility_flags = ["nodejs_compat"]

[vars]
PARIS_BASE_URL = "https://paris.dev.clickeen.com"
NEXT_PUBLIC_TOKYO_URL = "https://tokyo.dev.clickeen.com"

[env.production]
compatibility_flags = ["nodejs_compat"]
