name = "sanfrancisco-dev"
main = "src/index.ts"
compatibility_date = "2025-12-28"

[vars]
ENVIRONMENT = "dev"

[[kv_namespaces]]
binding = "SF_KV"
id = "f1abe003b9a8434699175b0c1ccd2603"

[[d1_databases]]
binding = "SF_D1"
database_name = "sanfrancisco_d1_dev"
database_id = "9ee059a3-538f-4b71-b2ea-f04b33e4897a"

[[r2_buckets]]
binding = "SF_R2"
bucket_name = "sanfrancisco-logs-dev"

[[queues.producers]]
binding = "SF_EVENTS"
queue = "sanfrancisco-events-dev"

[[queues.consumers]]
queue = "sanfrancisco-events-dev"
